[package]
name = "serenesia"
version = "0.1.0"
authors = ["ssc <ssc@apache.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vsknn_replay_from_file"
path = "src/bin/vsknn_replay_from_file.rs"

[dependencies]
timely = "0.11.1"
differential-dataflow = "0.11.0"
abomonation = "0.7.3"
abomonation_derive = "0.5.0"
itertools = "0.9.0"
fnv = "1.0.2"
csv = "1.0"
rand="0.6"